---
title: 'Part 1: Time Series'
author: "Bri Baker"
date: "2/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tsibble)
library(feasts)
library(fable)
library(here)
```

## Data as a tsibble


```{r}
energy <- read_csv(here("data", "energy.csv"))

energy_ts <- energy %>% 
  mutate(date = tsibble::yearmonth(month)) %>% 
  as_tsibble(key = NULL, index = date)

```


## Exploratory TS


### Raw data graph
```{r}
ggplot(data = energy_ts, aes(x = date, y = res_total)) +
  geom_line() +
  labs(y = "Residential energy consumption \n (Trillion BTU)")
```

### Seasonplot

```{r}
energy_ts %>% 
  gg_season(y = res_total) +
  theme_minimal() +
  labs(x = "month",
       y = "residential energy consumption (trillion BTU)")
```


### Subseries

```{r}
energy_ts %>% gg_subseries(res_total)
```

### Decomposition

```{r}
# Find STL decomposition
dcmp <- energy_ts %>%
  model(STL(res_total ~ season()))

# View the components
# components(dcmp)

# Visualize the decomposed components
components(dcmp) %>% autoplot() +
  theme_minimal()
```


### Autocorrelate

```{r}
energy_ts %>% 
  ACF(res_total) %>% 
  autoplot()
```


## Forecasting by Holt-Winters

```{r}
# Create the model:
energy_fit <- energy_ts %>%
  model(
    ets = ETS(res_total ~ season("M")) # multiplicative (opposed to "A" additive)
  )

# Forecast using the model 10 years into the future:
energy_forecast <- energy_fit %>% 
  forecast(h = "10 years")

# Plot just the forecasted values (with 80 & 95% CIs):
energy_forecast %>% 
  autoplot()

# Or plot it added to the original data:
energy_forecast %>% 
  autoplot(energy_ts)
```


### Assess Residuals

```{r}
# Append the predicted values (and residuals) to original energy data
energy_predicted <- broom::augment(energy_fit)

# Use View(energy_predicted) to see the resulting data frame
```


```{r}
## actual vs predicted
ggplot(data = energy_predicted) +
  geom_line(aes(x = date, y = res_total)) +
  geom_line(aes(x = date, y = .fitted), color = "red")


```


### residuals
```{r}
ggplot(data = energy_predicted, aes(x = .resid)) +
  geom_histogram()
```

other forecasting methods shown in key
